/* GENERATED by scripts/make-hero-placeholder.mjs. Do not edit by hand.
   Re-run: npm run placeholder */
export const heroBlurDataUrl =
  'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAQCdASoQAAwAAsBIJZwC06EO99FxJqAA/viSukdlYr9rXdkH03oAAAA='
