/* GENERATED by scripts/optimize-photos.mjs. Do not edit by hand. */
export const photos = {
  "bedroom-01-royal-bed": {
    "src": "/img/bedroom-01-royal-bed-1024.webp",
    "srcSet": "/img/bedroom-01-royal-bed-480.webp 480w, /img/bedroom-01-royal-bed-768.webp 768w, /img/bedroom-01-royal-bed-1024.webp 1024w",
    "width": 1024,
    "height": 573,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJZACdAD6d2DQYwAA/oc8vmXecGJQcLtiImQYt4DtJKngmkwvoQbuMkUbnXTeSlWMgTfiooH4jeOLk3Sx4NerzFqgAA==",
    "alpha": false
  },
  "bespoke-chairs-01": {
    "src": "/img/bespoke-chairs-01-1024.webp",
    "srcSet": "/img/bespoke-chairs-01-480.webp 480w, /img/bespoke-chairs-01-768.webp 768w, /img/bespoke-chairs-01-1024.webp 1024w",
    "width": 1024,
    "height": 584,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAkAA4BaJYwCdAYtzSRmBssccAD+QNa5PFrQwglXgGRpdL3Zq1uiQ3mZGpy0eayNz41u65q3rHgd373cAJqszlqWWLzO4cP6xevu91UmAAAA",
    "alpha": false
  },
  "detail-01-blue-sofa": {
    "src": "/img/detail-01-blue-sofa-1024.webp",
    "srcSet": "/img/detail-01-blue-sofa-480.webp 480w, /img/detail-01-blue-sofa-768.webp 768w, /img/detail-01-blue-sofa-1024.webp 1024w",
    "width": 1024,
    "height": 625,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAoAA4BaJagCdAEREd27+diYAAD+24AcTHm2o3Av7pafSJ7mcRebtF5voAu4fNWV146RkgNW9y6rxGI13jgIQlg/W+EeSTz/LxkAAAA=",
    "alpha": false
  },
  "dining-01-cream": {
    "src": "/img/dining-01-cream-1024.webp",
    "srcSet": "/img/dining-01-cream-480.webp 480w, /img/dining-01-cream-768.webp 768w, /img/dining-01-cream-1024.webp 1024w",
    "width": 1024,
    "height": 625,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAoAA4BaJbACdAENy2jxIIAAyjxcLnF4UXc9GFY1S5F4KXCyXjF6vy3coCnAEgRj+mzhFzDeq4j8EXrjc3Xv7FqK1ugAAAA=",
    "alpha": false
  },
  "dining-02-peach": {
    "src": "/img/dining-02-peach-1024.webp",
    "srcSet": "/img/dining-02-peach-480.webp 480w, /img/dining-02-peach-768.webp 768w, /img/dining-02-peach-1024.webp 1024w",
    "width": 1024,
    "height": 625,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAoAA4BaJbACdAYrJdW1jB35GPAA/t30en1BaXWbJ4XFAFMJ9HMUJ7sE8oSmRu7XuczfzoGI7oZyaw5qNEU9knGv2BpfSDovF7+rXvS7R9mJZXUlyMZWI8RAAA==",
    "alpha": false
  },
  "hero-sofa-01-frontal": {
    "src": "/img/hero-sofa-01-frontal-1024.webp",
    "srcSet": "/img/hero-sofa-01-frontal-480.webp 480w, /img/hero-sofa-01-frontal-768.webp 768w, /img/hero-sofa-01-frontal-1024.webp 1024w",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQABAAA4BaJbACdAC91L+YzDwA/tCeJVYBogWiChxmdRxzRwClpP1PqqcYePSgAuxPhtfXG7LddfKy7Nkuw/ZmdggbUTsvu1XQQjuatp8Mga/4AAA=",
    "alpha": false
  },
  "living-01-beige-set": {
    "src": "/img/living-01-beige-set-1024.webp",
    "srcSet": "/img/living-01-beige-set-480.webp 480w, /img/living-01-beige-set-768.webp 768w, /img/living-01-beige-set-1024.webp 1024w",
    "width": 1024,
    "height": 625,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAoAA4BaJZACdACXjpfLQ4AA++P7suEmV4EhOxkwrXO5j3SIP840z+aOrZtedkgGJMR906sMgImyQFtxiw8Pk2ygTzQAAAA=",
    "alpha": false
  },
  "living-02-blue-pair": {
    "src": "/img/living-02-blue-pair-1024.webp",
    "srcSet": "/img/living-02-blue-pair-480.webp 480w, /img/living-02-blue-pair-768.webp 768w, /img/living-02-blue-pair-1024.webp 1024w",
    "width": 1024,
    "height": 645,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAoAA4BaJbACdAEQA4+qPflHAAD+vGWoPgWo/SMeGkOqXEUIsQ55SV9zdHgk9M700Gbrs0BsxYricK7u1CkTvjY/kFDHUU+ABN0QAAA=",
    "alpha": false
  },
  "living-03-wood-set": {
    "src": "/img/living-03-wood-set-1024.webp",
    "srcSet": "/img/living-03-wood-set-480.webp 480w, /img/living-03-wood-set-768.webp 768w, /img/living-03-wood-set-1024.webp 1024w",
    "width": 1024,
    "height": 625,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoQAAoAA4BaJaACdACDOB8AAPvc3Fn76su7Gb9+Rqf8Wfl1su2q2gEun8t3fRxaAyyg4Ej/t9mrxo10S1dEOv+vs/lDpYpap6bDk1E7cnK0VlYoAAA=",
    "alpha": false
  },
  "office-storage-01-black-cabinet": {
    "src": "/img/office-storage-01-black-cabinet-1024.webp",
    "srcSet": "/img/office-storage-01-black-cabinet-480.webp 480w, /img/office-storage-01-black-cabinet-768.webp 768w, /img/office-storage-01-black-cabinet-1024.webp 1024w",
    "width": 1024,
    "height": 563,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAkAA4BaJZACdAEf/xIWccmAAP7mH48mzbImsmBM1Cf4EfpRtOTflJM5uWtRD4DT6wRFh4xIMLlB3KiGYI5dsAA=",
    "alpha": false
  },
  "people-owner-heaven-furniture": {
    "src": "/img/people-owner-heaven-furniture-2476.webp",
    "srcSet": "/img/people-owner-heaven-furniture-480.webp 480w, /img/people-owner-heaven-furniture-768.webp 768w, /img/people-owner-heaven-furniture-1024.webp 1024w, /img/people-owner-heaven-furniture-1600.webp 1600w, /img/people-owner-heaven-furniture-2476.webp 2476w",
    "width": 2476,
    "height": 1728,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAA4BaJQBOgCB/oHmZf50/AAD+7WFnRT+zKG59fQoBxv7hatvSP7AMlydcs4hQXH8e7fI9mbv0TFpvgEL/cwN3zKZ3f3t11WME0AA=",
    "alpha": false
  },
  "hero-backdrop": {
    "src": "/img/hero-backdrop.webp",
    "srcSet": "/img/hero-backdrop.webp 1280w",
    "width": 1280,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoQABAAA4BaJagCdADYoUQAAP6oQ0jDrbsAsiNQ4xYL7UGNl92q6CEdzVtPhf89gAA="
  }
} as const

export type PhotoKey = keyof typeof photos
